Generate QAPP Error
Eastern-Research-Group/AquaQAPP pull request #504
Opened 2020-08-10 17:18 UTC by TylerGoulskiERG

Added alert for when Generate QAPP fails. The alert displays informing the user to try again. Generate QAPP button resets.

2020-08-10 17:36 UTC, dpgalloway requested changes

2020-08-10 17:36 UTC, dpgalloway commented on client/src/components/shared/Alert.vue
> +    fadeOut: {
Remove this (not being used)

2020-08-10 17:36 UTC, dpgalloway commented on client/src/components/app/ProgressBar.vue
> +    // autoCloseError() {
Remove this commented out code

2020-08-10 17:36 UTC, dpgalloway commented on client/src/components/app/ProgressBar.vue
> +  async mounted() {
Confirm that this mounted function is necessary? Looks like it would just set the generateError to undefined since there's no second argument there. If it's necessary to clear out any past value, let's add `false` for clarity.

2020-08-10 19:18 UTC, TylerGoulskiERG commented on client/src/components/shared/Alert.vue
> +    fadeOut: {
Removed in 740681f

2020-08-10 19:18 UTC, TylerGoulskiERG commented on client/src/components/app/ProgressBar.vue
> +    // autoCloseError() {
Removed in 740681f

2020-08-10 19:18 UTC, TylerGoulskiERG commented on client/src/components/app/ProgressBar.vue
> +  async mounted() {
You're right, this is not needed. Removed in 740681f.

2020-08-12 21:55 UTC, dpgalloway approved these changes

2020-08-12 21:55 UTC, merged